php artisan make:migration create_users_table
php artisan make:migration create_accounts_table
php artisan make:migration create_trades_table
php artisan make:migration create_trade_statuses_table
php artisan make:migration create_weekly_forecasts_table
php artisan make:migration create_plans_checklists_table
php artisan make:migration create_reports_table
php artisan make:migration create_trade_annulments_table
